name: Budowanie pliku .exe

on:
  schedule:
    - cron:  '0 12 * * 1' # Uruchamia co tydzień o 12:00 w poniedziałek.
  push:
    branches: [ master ] # Uruchamia po każdym pushu na mastera.
  workflow_dispatch: # Umożliwia uruchomienie ręczne.

jobs:
  build:
    runs-on: windows-latest # Ustawia najnowszy dostępny serwer Windows.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Ustawia wersję Pythona.

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install jsonlib
        pip install xmltodict
        pip install pyyaml

    - name: Upload .exe file
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: main.exe
